
name: CI for the backend go server
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile.go
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/benedicthomuth/iot4Dobot/server:latest